baseURL = "https://xiaowing.github.io/"
languageCode = "zh-cn"
title = "小wing的驿站"
author = "Yi Yi"
theme = "blackburn"
# Shown in the side menu
copyright = "&copy; Licensed under CC BY-NC-SA."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "wing's dak"
  brand = "小wing的驿站"
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  # [[menu.main]]
  #   name = "Contact"
  #   pre = "<i class='fa fa-phone fa-fw'></i>"
  #   weight = 3
  #   url = "/contact/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "xiaowing"
  weibo = "u/3304350204"
  instagram = "xiaowing"
  github = "xiaowing"
  